---
minimum_pre_commit_version: 1.15.2
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
          - id: check-merge-conflict # Check for files that contain merge conflict strings.
            language_version: python3
          - id: trailing-whitespace # Trims trailing whitespace.
            args: [--markdown-linebreak-ext=md]
            language_version: python3
          - id: mixed-line-ending # Replaces or checks mixed line ending.
            args: [--fix=lf]
            language_version: python3
          - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
        # exclude: tests/fake_.*\.key
            language_version: python3
          - id: check-ast         # Simply check whether files parse as valid python.
            language_version: python3
          - id: check-yaml
          - id: check-json
          - id: check-symlinks
          - id: detect-private-key
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: master
      hooks:
          - id: isort
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: master
      hooks:
          - id: autopep8
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: master
      hooks:
          - id: mypy
    - repo: https://github.com/asottile/blacken-docs
      rev: master
      hooks:
          - id: blacken-docs
    - repo: https://github.com/asottile/dead
      rev: master
      hooks:
          - id: dead
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: master
      hooks:
          - id: forbid-binary
          - id: git-check
          #- id: git-dirty
          - id: markdownlint
          #- id: shellcheck
          #- id: shfmt
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: master
      hooks:
          - id: yamlfmt
    - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
      rev: master
      hooks:
          - id: python-safety-dependencies-check

    - repo: https://github.com/motet-a/jinjalint
      rev: master
      hooks:
          - id: jinjalint
    - repo: https://github.com/warpnet/salt-lint
      rev: v0.2.2
      hooks:
          - id: salt-lint
            name: Salt-lint
            description: This hook runs salt-lint.
            entry: salt-lint
            language: python
            files: \.(sls)$

    - repo: https://github.com/psf/black
      rev: stable
      hooks:
          - id: black
            language_version: python3



## EOF
